### PR TITLE
need to use the right fireroad link

### PR DESCRIPTION
**Pull request by npfoss**
Hey @ttpcodes, could you take over this PR and add `FIREROAD_LINK` (in both `Auth.vue` and `MainPage.vue`) to the webpack stuff like the other thing please? It should be `fireroad-dev` for local and /dev/, and `fireroad` for prod.

### CODE REVIEW

**Comment by georgiashay** [comment]
I can do this

**Comment by ttpcodes** [comment]
@georgiashay Don't worry about it, I already started working on the PR.

**Comment by ttpcodes** [comment]
Assuming I didn't miss anything, these two commits should set `FIREROAD_URL` from `webpack` now.

**Comment by npfoss** [comment]
I tested as much as I could and it looks good!

**Pull request merged**
