### PR TITLE
Toolbar icons

### PR DESCRIPTION
**Pull request by georgiashay**
Made toolbar have login/logout, import/export icons when screen is small
Made the class search resize to fit on small screens
Added scrollbar if the class search can't fit the filters (I know we have disliked scroll bars in the past, so if this looks terrible we should remove it, it's the last commit)

### CODE REVIEW

**Comment by npfoss** [comment]
I'm too tired, and this is noncritical for MVP, sorry... I do appreciate it though and will take a look later.

**Comment by georgiashay** [comment]
don't merge this yet something is wrong with it

**Comment by georgiashay** [comment]
image

**Comment by georgiashay** [comment]
This should be ready to merge now

**Comment by wishdasher** [comment]
The search bar is no longer set with the right side of the screen. Is this intentional, and if so, why?

**Comment by georgiashay** [comment]
Not intentional - thought it was at the right side last night but I’ll take a look later today

**Comment by npfoss** [comment]
oh, dammit, sorry I didn't catch that. thanks for noticing.

I just tried the simple solution of adding a `<v-spacer>` and that wasn't sufficient fyi

**Comment by georgiashay** [comment]
This is what it looks like for me

image

**Comment by wishdasher** [comment]
image

**Comment by wishdasher** [comment]
I think you have to zoom out a bit.

**Comment by georgiashay** [comment]
I think this is because of the resizing of said searchbar on small screens that I added.  Will look into this

**Comment by npfoss** [comment]
This is now fixed, for the record

**Pull request merged**
