### PR TITLE
Change mechanism for adding course to an autocomplete

### PR DESCRIPTION
**Pull request by wishdasher**
Remaining todos:
- order courses, I think this will have to be manually parsed :/
- change select items to have more info, this can be done with scoped slots but I haven't figured it out yet

### CODE REVIEW

**Comment by npfoss** [comment]
I'm seeing some compile errors. Can you take a look while I review the rest?

**Comment by georgiashay** [comment]
I am getting duplicate key warnings on a road that has the same major twice

**Comment by georgiashay** [comment]
Also for remaining todos would be disambiguating the courses that look the same 
image

**Comment by npfoss** [comment]
Are the different on hover? I think that's what we decided was best

**Comment by georgiashay** [comment]
I don't think they are different on hover, or it isn't working for me

**Comment by wishdasher** [comment]
The courses are ordered now. Major, minor, then other. Within each, by number and then letter. 6-14 is before 6-2, 6-3, etc., but this is a super edge case.

I don't really want to display the long name on hover because it's not necessary for most of the courses. I was wondering if the `medium-title` field could be disambiguated for 18 Major, 21W, etc. Is there a concrete reason not to? @venkatesh-sivaraman

**Comment by wishdasher** [comment]
(For documentation): Addressing #37, #38, #59 in this PR

**Comment by npfoss** [comment]
For some reason I'm still getting this compile error after removing `node_modules` and reinstalling everything:
>   Errors compiling template:

  <template v-slot> can only appear at the root level inside the receiving the component

  4  |  <v-flex style="padding: 0px 18px 0px 18px; overflow: auto;">
  5  |    <div style="display: flex; align-content: space-between; margin: 12px 0px;">
  6  |      <template v-slot:prepend>
     |      ^^^^^^^^^^^^^^^^^^^^^^^^^
  7  |        <v-icon
     |  ^^^^^^^^^^^^^
  8  |          :key="`icon-${isEditing}`"
     |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  9  |          :color="isEditing ? 'success' : 'info'"
     |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  10 |          @click="isEditing = !isEditing"
     |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  11 |          v-text="isEditing ? 'save' : 'edit'"
     |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  12 |          style="margin-right: 8px;"
     |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  13 |        ></v-icon>
     |  ^^^^^^^^^^^^^^^^
  14 |      </template>
     |  ^^^^^^^^^^^^^^^

**Comment by wishdasher** [comment]
That's weird. I just removed `node_modules` and reinstalled too, and it still works for me.

**Comment by npfoss** [comment]
ok trying to figure that out now...

In the meantime, I should have asked before merging that other branch but it definitely caused merge conflicts with everything

**Comment by wishdasher** [comment]
I'll rebase.

**Comment by npfoss** [comment]
This doesn't have any noticeable differences from what you see, right?
image
(I just removed the template and put the slot thing on the icon)

**Pull request merged**
